import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProvinceCodesService {

  public states: {};

  constructor() {
    this.states = {
      US : [
        { code: 'AL', name: 'Alabama'},
        { code: 'AK', name: 'Alaska'},
        { code: 'AZ', name: 'Arizona'},
        { code: 'AR', name: 'Arkansas'},
        { code: 'CA', name: 'California'},
        { code: 'CO', name: 'Colorado'},
        { code: 'CT', name: 'Connecticut'},
        { code: 'DE', name: 'Delaware'},
        { code: 'FL', name: 'Florida'},
        { code: 'GA', name: 'Georgia'},
        { code: 'HI', name: 'Hawaii'},
        { code: 'ID', name: 'Idaho'},
        { code: 'IL', name: 'Illinois'},
        { code: 'IN', name: 'Indiana'},
        { code: 'IA', name: 'Iowa'},
        { code: 'KS', name: 'Kansas'},
        { code: 'KY', name: 'Kentucky'},
        { code: 'LA', name: 'Louisiana'},
        { code: 'ME', name: 'Maine'},
        { code: 'MD', name: 'Maryland'},
        { code: 'MA', name: 'Massachusetts'},
        { code: 'MI', name: 'Michigan'},
        { code: 'MN', name: 'Minnesota'},
        { code: 'MS', name: 'Mississippi'},
        { code: 'MO', name: 'Missouri'},
        { code: 'MT', name: 'Montana'},
        { code: 'NE', name: 'Nebraska'},
        { code: 'NV', name: 'Nevada'},
        { code: 'NH', name: 'New Hampshire'},
        { code: 'NJ', name: 'New Jersey'},
        { code: 'NM', name: 'New Mexico'},
        { code: 'NY', name: 'New York'},
        { code: 'NC', name: 'North Carolina'},
        { code: 'ND', name: 'North Dakota'},
        { code: 'OH', name: 'Ohio'},
        { code: 'OK', name: 'Oklahoma'},
        { code: 'OR', name: 'Oregon'},
        { code: 'PA', name: 'Pennsylvania'},
        { code: 'RI', name: 'Rhode Island'},
        { code: 'SC', name: 'South Carolina'},
        { code: 'SD', name: 'South Dakota'},
        { code: 'TN', name: 'Tennessee'},
        { code: 'TX', name: 'Texas'},
        { code: 'UT', name: 'Utah'},
        { code: 'VT', name: 'Vermont'},
        { code: 'VA', name: 'Virginia'},
        { code: 'WA', name: 'Washington'},
        { code: 'WV', name: 'West Virginia'},
        { code: 'WI', name: 'Wisconsin'},
        { code: 'WY', name: 'Wyoming'},
        { code: 'DC', name: 'District of Columbia district'},
        { code: 'AS', name: 'American Samoa outlying area'},
        { code: 'GU', name: 'Guam outlying area'},
        { code: 'MP', name: 'Northern Mariana Islands outlying area'},
        { code: 'PR', name: 'Puerto Rico outlying area'},
        { code: 'UM', name: 'United States Minor Outlying Islands outlying area'},
        { code: 'VI', name: 'Virgin Islands, U.S. outlying area'}
      ],
      MX : [
        { code: 'AG', name: 'Aguascalientes'},
        { code: 'BC', name: 'Baja California'},
        { code: 'BS', name: 'Baja California Sur'},
        { code: 'CM', name: 'Campeche'},
        { code: 'CS', name: 'Chiapas'},
        { code: 'CH', name: 'Chihuahua'},
        { code: 'CO', name: 'Coahuila'},
        { code: 'CL', name: 'Colima'},
        { code: 'DF', name: 'Mexico City'},
        { code: 'DG', name: 'Durango'},
        { code: 'GT', name: 'Guanajuato'},
        { code: 'GR', name: 'Guerrero'},
        { code: 'HG', name: 'Hidalgo'},
        { code: 'JA', name: 'Jalisco'},
        { code: 'EM', name: 'México'},
        { code: 'MI', name: 'Michoacán'},
        { code: 'MO', name: 'Morelos'},
        { code: 'NA', name: 'Nayarit'},
        { code: 'NL', name: 'Nuevo León'},
        { code: 'OA', name: 'Oaxaca'},
        { code: 'PU', name: 'Puebla'},
        { code: 'QT', name: 'Querétaro'},
        { code: 'QR', name: 'Quintana Roo'},
        { code: 'SL', name: 'San Luis Potosí'},
        { code: 'SI', name: 'Sinaloa'},
        { code: 'SO', name: 'Sonora'},
        { code: 'TB', name: 'Tabasco'},
        { code: 'TM', name: 'Tamaulipas'},
        { code: 'TL', name: 'Tlaxcala'},
        { code: 'VE', name: 'Veracruz'},
        { code: 'YU', name: 'Yucatán'},
        { code: 'ZA', name: 'Zacatecas'},
      ],
      CA : [
        { code: 'AB', name: 'Alberta Alberta	province'},
        { code: 'BC', name: 'British Columbia Colombie-Britannique province'},
        { code: 'MB', name: 'Manitoba	Manitoba province'},
        { code: 'NB', name: 'New Brunswick Nouveau-Brunswick province'},
        { code: 'NL', name: 'Newfoundland and Labrador Terre-Neuve-et-Labrador province'},
        { code: 'NS', name: 'Nova Scotia Nouvelle-Écosse province'},
        { code: 'ON', name: 'Ontario Ontario	province'},
        { code: 'PE', name: 'Prince Edward Island Île-du-Prince-Édouard province'},
        { code: 'QC', name: 'Quebec	Québec province'},
        { code: 'SK', name: 'Saskatchewan Saskatchewan province'},
        { code: 'NT', name: 'Northwest Territories Territoires du Nord-Ouest territory'},
        { code: 'NU', name: 'Nunavut Nunavut territory'},
        { code: 'YT', name: 'Yukon Yukon territory'},
      ]
    };
  }

  public getStates() {
    return this.states;
  }
}
